version: '3.0'

services: 
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes: 
      - .:/code
    ports: 
      - 8000:8000
    env_file: 
      - app-env.list
    networks: 
      - books
    depends_on: 
      - postgres
  
  postgres:
    container_name: postgres
    image: postgres:latest
    ports: 
      - 5432:5432
    volumes: 
      - ~/.docker_db_data/postgres:/var/lib/postgresql/data
    env_file: 
      - postgres-env.list
    restart: always
    networks: 
      - books
  
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    env_file: 
      - postgres-env.list
    volumes: 
      - ~/.docker_db_data/pgadmin:/var/lib/pgadmin
    networks: 
      - books
    restart: always
    ports: 
      - 5050:5050

  nginx:
    container_name: nginx
    image: nginx:alpine
    restart: unless-stopped
    ports: 
      - 80:80
    volumes: 
      - ./nginx-conf:/etc/nginx/conf.d
    networks: 
      - books
    depends_on: 
      - web


networks: 
  books:
    driver: bridge

